// Generated by gencpp from file test_service/example_serviceRequest.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_MESSAGE_EXAMPLE_SERVICEREQUEST_H
#define TEST_SERVICE_MESSAGE_EXAMPLE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_service
{
template <class ContainerAllocator>
struct example_serviceRequest_
{
  typedef example_serviceRequest_<ContainerAllocator> Type;

  example_serviceRequest_()
    : a(0.0)
    , h(0.0)  {
    }
  example_serviceRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , h(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::test_service::example_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_service::example_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct example_serviceRequest_

typedef ::test_service::example_serviceRequest_<std::allocator<void> > example_serviceRequest;

typedef boost::shared_ptr< ::test_service::example_serviceRequest > example_serviceRequestPtr;
typedef boost::shared_ptr< ::test_service::example_serviceRequest const> example_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_service::example_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_service::example_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_service::example_serviceRequest_<ContainerAllocator1> & lhs, const ::test_service::example_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.h == rhs.h;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_service::example_serviceRequest_<ContainerAllocator1> & lhs, const ::test_service::example_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_service::example_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service::example_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service::example_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service::example_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service::example_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service::example_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_service::example_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0ca8f0a58db916c405d9eda9fedf97b";
  }

  static const char* value(const ::test_service::example_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0ca8f0a58db916cULL;
  static const uint64_t static_value2 = 0x405d9eda9fedf97bULL;
};

template<class ContainerAllocator>
struct DataType< ::test_service::example_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_service/example_serviceRequest";
  }

  static const char* value(const ::test_service::example_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_service::example_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n"
"float32 h\n"
;
  }

  static const char* value(const ::test_service::example_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_service::example_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct example_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_service::example_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_service::example_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERVICE_MESSAGE_EXAMPLE_SERVICEREQUEST_H
