// Generated by gencpp from file test_service/example_service.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_MESSAGE_EXAMPLE_SERVICE_H
#define TEST_SERVICE_MESSAGE_EXAMPLE_SERVICE_H

#include <ros/service_traits.h>


#include <test_service/example_serviceRequest.h>
#include <test_service/example_serviceResponse.h>


namespace test_service
{

struct example_service
{

typedef example_serviceRequest Request;
typedef example_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct example_service
} // namespace test_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_service::example_service > {
  static const char* value()
  {
    return "38f137fdee9dd66103a5094dffd6e0e8";
  }

  static const char* value(const ::test_service::example_service&) { return value(); }
};

template<>
struct DataType< ::test_service::example_service > {
  static const char* value()
  {
    return "test_service/example_service";
  }

  static const char* value(const ::test_service::example_service&) { return value(); }
};


// service_traits::MD5Sum< ::test_service::example_serviceRequest> should match
// service_traits::MD5Sum< ::test_service::example_service >
template<>
struct MD5Sum< ::test_service::example_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_service::example_service >::value();
  }
  static const char* value(const ::test_service::example_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service::example_serviceRequest> should match
// service_traits::DataType< ::test_service::example_service >
template<>
struct DataType< ::test_service::example_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::test_service::example_service >::value();
  }
  static const char* value(const ::test_service::example_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_service::example_serviceResponse> should match
// service_traits::MD5Sum< ::test_service::example_service >
template<>
struct MD5Sum< ::test_service::example_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_service::example_service >::value();
  }
  static const char* value(const ::test_service::example_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service::example_serviceResponse> should match
// service_traits::DataType< ::test_service::example_service >
template<>
struct DataType< ::test_service::example_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::test_service::example_service >::value();
  }
  static const char* value(const ::test_service::example_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SERVICE_MESSAGE_EXAMPLE_SERVICE_H
