set(_CATKIN_CURRENT_PACKAGE "test_publisher")
set(test_publisher_VERSION "0.0.0")
set(test_publisher_MAINTAINER "pi <pi@todo.todo>")
set(test_publisher_PACKAGE_FORMAT "2")
set(test_publisher_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_publisher_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_publisher_BUILDTOOL_DEPENDS "catkin")
set(test_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(test_publisher_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_publisher_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_publisher_TEST_DEPENDS )
set(test_publisher_DOC_DEPENDS )
set(test_publisher_URL_WEBSITE "")
set(test_publisher_URL_BUGTRACKER "")
set(test_publisher_URL_REPOSITORY "")
set(test_publisher_DEPRECATED "")