#  Формат топика в который выводим все что верхний уровень посылает в блок Body
#	uint32_t id = 0; // Номер команды по порядку
#	uint32_t time = 0; // Время в течении которого нужно двигаться
#	int32_t napravlenie = 0;
#	int32_t command = 0; // Команда для выполнения
#	float speed = 0;	 // Скорость которую нужно установить
#	float radius = 0;	 // Радиус по которому нужно двигаться
#	float way = 0;		 // Путь который нужно проехать

	uint32 id
	uint32 time
	int32 napravlenie 
	int32 command 
	float32 speed 
	float32 radius 
	float32 way