// Generated by gencpp from file my_msgs/HL_to_Control.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_HL_TO_CONTROL_H
#define MY_MSGS_MESSAGE_HL_TO_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct HL_to_Control_
{
  typedef HL_to_Control_<ContainerAllocator> Type;

  HL_to_Control_()
    {
    }
  HL_to_Control_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::my_msgs::HL_to_Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::HL_to_Control_<ContainerAllocator> const> ConstPtr;

}; // struct HL_to_Control_

typedef ::my_msgs::HL_to_Control_<std::allocator<void> > HL_to_Control;

typedef boost::shared_ptr< ::my_msgs::HL_to_Control > HL_to_ControlPtr;
typedef boost::shared_ptr< ::my_msgs::HL_to_Control const> HL_to_ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::HL_to_Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::HL_to_Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace my_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::HL_to_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::HL_to_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::HL_to_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::HL_to_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::HL_to_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::HL_to_Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::HL_to_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::my_msgs::HL_to_Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::HL_to_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/HL_to_Control";
  }

  static const char* value(const ::my_msgs::HL_to_Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::HL_to_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#  Формат топика в который выводим все что верхний уровень посылает в блок Control\n"
;
  }

  static const char* value(const ::my_msgs::HL_to_Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::HL_to_Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HL_to_Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::HL_to_Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::my_msgs::HL_to_Control_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_HL_TO_CONTROL_H
